#!/bin/bash

FREKVENSSITIEDOSTO=avainsana-frekvenssit.csv

rm -f ${FREKVENSSITIEDOSTO}

while read KAPPALETIEDOSTO;
do
    cat ${KAPPALETIEDOSTO}.org | tr '[:punct:]' ' ' | tr '([])' ' ' | tr '[:digit:]' ' ' | tr -s ' ' | awk '
  BEGIN { ORS = "," }
  FILENAME == ARGV[1] {word[$1]=0; next}
  {
    for (i=1; i<=NF; i++) {
      if ($i in word) word[$i]++
    }
  }
  END {for (w in word) print word[w] ; printf "\n" }
' avainsanat.txt - | sed 's/,$//' >> ${FREKVENSSITIEDOSTO}
done < kappaletiedostot.txt

