# -*- org-autonum-enable: t; -*-

* Piirtäminen lausekkeiden avulla <<1>>
** Piirtoikkunan pisteen koordinaatit <<1.1>>
   
   Processing-ohjelmointikielessä piirretään kuvioita ja animaatioita
   piirtoikkunaan. Piirtoikkunan eri kohtiin viitataan \(x\)- ja
   \(y\)-koordinaateilla. Esimerkiksi pisteen \((70, 40)\)
   \(x\)-koordinaatti on 70 ja \(y\)-koordinaatti 40. Toisin kuin
   matematiikassa, piirtoikkunassa piste \((0, 0)\) on /vasemmassa
   yläkulmassa/ ja \(y\)-koordinaatin arvot kasvavat
   /alaspäin/. Seuraavaan kuva esittää piirtoikkunaa, jonka leveys on
   600 ja korkeus 400. Kuvaan on piirretty myös kaikkien ikkunan
   kulmapisteiden koordinaatit sekä pisteiden \((70, 40)\) ja \((220,
   130)\) kohdat.

   
   #+NAME: koordinaatisto
   #+BEGIN_SRC asymptote :exports none
     int LEVEYS = 600;
     int KORKEUS = 400;
     size (LEVEYS, KORKEUS);
     filldraw (xscale (LEVEYS) * yscale (KORKEUS) * unitsquare, lightgray);
     // muunnos Processing-koordinaatistosta perinteiseen koordinaatistoon
     transform T = shift ((0, 400)) * yscale (-1); 
     real s = -.05 * LEVEYS; // akselien translaatio pois ikkunan reunalta
     draw ("$x$", T * shift ((0, s)) * ((0, 0) -- (LEVEYS, 0)), LeftSide, EndArrow);
     draw ("$y$", T * shift ((2*s, 0)) * ((0, 0) -- (0, KORKEUS)), EndArrow);

   #+END_SRC

   #+NAME: pisteita-koordinaatistossa
   #+BEGIN_SRC asymptote :noweb yes :file pisteita-koordinaatistossa.svg 
     <<koordinaatisto>>
     pair A = (70, 40);
     pair B = (220, 130);

     for (pair P : new pair[] {A, B})
       dot ((string) P, T * P, NE);
     for (int x : new int[] {0, LEVEYS})
       for (int y : new int[] {0, KORKEUS})
         {
           pair P = (x, y);
           dot ((string) P, T * P, (x == 0 ? W : E));
         }
   #+END_SRC

   #+RESULTS: pisteita-koordinaatistossa
   [[file:pisteita-koordinaatistossa.svg]]

   Eräs peruskuvioista on suorakulmio (englanniksi
   /rectangle/). Seuraavassa esimerkissä piirretään suorakulmio
   ikkunaan, jonka koko on $600\times 400$ pikseliä. Piirtoikkuna on
   väriltään harmaa, ja piirretyssä valkoisessa suorakulmiossa on
   musta reunus.
   #+BEGIN_SRC processing :exports both
     size (600, 400);
     rect (70, 40, 150, 90);
   #+END_SRC

   Lauseke ~size (600, 400);~ avaa piirtoikkunan, jonka leveys on 600
   pikseliä ja korkeus 400 pikseliä. Lauseke ~rect (70, 40, 150, 90);~
   piirtää suorakaiteen, jonka vasen yläkulma on kohdassa \((70, 40)\)
   ja jonka leveys on 150 ja korkeus 90. Koska suorakaiteen yläkulman
   \(x\)-koordinaatin ja leveyden summa on \[ 70 + 150 = 220, \] ja
   yläkulman \(y\)-koordinaatin ja korkeuden summa on \[ 40 + 90 =
   130, \] suorakaiteen oikea alakulma on samassa kohdassa kuin yllä
   olevaan kuvaan piirretty piste \((220, 130)\).

   Tarkalleen ottaen suorakulmio koostuu pienistä neliöistä eli
   /pikseleistä/, mikä vaikuttaa hieman oikean alakulman tarkkoihin
   koordinaatteihin. Tähän palataan kappaleessa [[txt:pikseli]].
** Ohjelmarivin muoto
   Tietokoneohjelma koostuu tyypillisesti /ohjelmariveistä/, joita
   edellä olevasta ohjelmasta löytyy kaksi. Processing-ohjelma on
   hyvin tarkka monista ohjelmarivin yksityiskohdista. Jotkut asiat
   ohjelmoija voi itse päättää.

   Edellä olevasta ohjelmasta voidaan jättää pois kaikki tyhjä tila
   eli välilyönnit, ja ohjelma toimii silti samalla
   tavalla. Välilyöntien käyttäminen on siis tyylikysymys.
   
   #+BEGIN_SRC processing :exports both
     size(600,400);
     rect(70,40,150,90);
   #+END_SRC

   Melkein kaikki muut muutokset johtavat siihen, että ohjelma ei joko
   toimi tai lopputulos muuttuu. Ennen kaikkea
   - ohjelmarivin lopussa täytyy olla puolipiste eli ~;~
   - sanat ~size~ ja ~rect~ täytyy kirjoittaa pienillä kirjaimilla
   - sulkujen ~()~ täytyy olla tavalliset sulut, ei esimerkiksi
     aaltosulut ~{}~ tai hakasulut ~[]~
   - sulkujen sisällä olevien lukujen täytyy olla eroteltuina
     toisistaan pilkuilla.

   Kokeile tehdä muutoksia riveihin ja katso, mitä tapahtuu kun yrität
   suorittaa ohjelman.
** Muita kuvioita
   Suorakaiteen piirtämiseen käytetään yllä /funktiota/
   ~rect()~. Funktioiden nimiin viitataan usein laittamalla sulut
   nimen perään, jotta tiedetään kyseeessä olevan nimenomaan
   funktio. Tällöin sulkujen sisältö jätetään yksinkertaisuuden vuoksi
   monesti tyhjäksi.

   Funktio ~rect()~ piirtää suorakaiteen, jonka sivut ovat
   piirtoikkunan sivujen suuntaiset. Muunlaisia nelikulmioita voidaan
   piirtää funktiolla ~quad()~, jonka nimi tulee englannin kielen
   nelikulmiota tarkoittavasta sanasta /quadrilateral/. Tällöin
   sulkujen sisään laitetaan kaikkien neljän pisteen koordinaatit
   järjestyksessä joko myötä- tai vastapäivään kuviota
   kiertäen. Seuraavassa esimerkissä piirretään nelikulmio, jonka
   kärkipisteet ovat myötäpäivään kiertäen \((70, 40)\), \((220, 40)\),
   \((220, 130)\) sekä \((70, 130)\). Lopputuloksena saadaan
   samankaltainen suorakulmio kuin edellisessä esimerkissä.
   
   #+BEGIN_SRC processing :exports both
     size (600, 400);
     quad (70, 40, 220, 40, 220, 130, 70, 130);
   #+END_SRC

   Kolmioita voidaan piirtää vastaavalla funktiolla ~triangle()~ jolle
   annetaan kolmen kärkipisteen koordinaatit. 

   Mikäli kuvioita piirretään useampia, seuraava piirretään edellisen
   päälle. Seuraavissa esimerkeissä vain piirtokomentojen järjestys on
   vaihdettu.

   #+BEGIN_SRC processing :exports both
     size (600, 400);
     triangle (50, 50, 50, 350, 350, 350);
     quad (50, 200, 200, 350, 350, 200, 200, 50);
   #+END_SRC

   #+BEGIN_SRC processing :exports both
     size (600, 400);
     quad (50, 200, 200, 350, 350, 200, 200, 50);
     triangle (50, 50, 50, 350, 350, 350);
   #+END_SRC
** Kuvion suunnitteleminen
   Kuvioiden kärkipisteiden koordinaatit kannattaa usein suunnitella
   kynällä ja paperilla ennen kuvan piirtämistä
   tietokoneella. Esimerkiksi yllä oleva kahden kuvion kuva
   suunniteltiin seuraavasti. Tavoitteena oli piirtää kuvan kaltainen
   kuvio, jossa on 
   - suorakulmainen tasakylkinen kolmio sekä
   - neliö, jonka kaksi kärkipistettä ovat kolmion kylkien
     keskikohdissa.
   Kolmion yhdeksi pisteeksi valittiin $(50, 50)$ ja kylkien
   pituudeksi 300.

   Suunnittelu voidaan yleensä tehdä useammalla eri tavalla. Tässä
   tapauksessa kärkipisteet voidaan etsiä vaikkapa seuraavasti alla
   olevan kuvan mukaisesti.
   1. Piste \(A (50, 50)\) on annettu.
   2. Pisteellä $B$ on sama \(x\)-koordinaatti kuin pisteellä \(A.\)
      Koska kolmion kyljen pituus on 300 ja \(y\)-akselin arvot
      kasvavat alaspäin, pisteen $B$ \(y\)-koordinaatti on 300
      yksikköä suurempi kuin pisteen \(A\). Niinpä \(B(50, 350).\)
   3. Pisteillä $B$ ja $C$ on sama \(y\)-koordinaatti, mutta pisteen
      \(C\) \(x\)-koordinaatti on 300 suurempi. Täten \(C(350, 350).\)
   4. Piste \(D\) on pisteiden $A$ ja $B$ puolivälissä, joten \(D(50,
      200).\) Vastaavasti \(E\) on pisteiden $B$ ja $C$ puolivälissä,
      jolloin \(E(200, 350).\)
   5. Koska $DEFG$ on neliö, pisteellä $F$ on sama \(x\)-koordinaatti
      kuin pisteellä $C$ ja sama \(y\)-koordinaatti kuin pisteellä
      \(D,\) joten \(F(350, 200).\)
   6. Vastaavasti pisteellä $G$ on on sama \(x\)-koordinaatti kuin
      pisteellä $E$ ja sama \(y\)-koordinaatti kuin pisteellä \(A,\)
      joten \(G(200, 50).\)
    
   #+BEGIN_SRC asymptote :file kolmio-nelio.svg :noweb yes
     <<koordinaatisto>>
     pair A = (50, 50);
     int s = 300; // sivun pituus
     pair B = shift ((0, s)) * A;
     pair C = shift ((s, 0)) * B;

     draw (T * (A -- B -- C -- cycle), dashed);
     pair D = midpoint (A -- B);
     pair Ep = midpoint (B -- C);
     pair F = (C.x, D.y);
     pair G = (Ep.x, A.y);
     draw (T * (D -- Ep -- F -- G -- cycle), dashed);
     pair[] points = {A, B, C, D, Ep, F, G};
     string[] labels = {"$A$", "$B$", "$C$", "$D$", "$E$", "$F$", "$G$"};
     for (int i = 0; i < points.length; ++i)
       {
         pair P = points [i];
         dot (labels [i] + (string) P, T * P, (P.y == A.x + s ? S : E));
       }
   #+END_SRC

** Tehtävät
  1. Piirrä \(800\times 600\)-kokoiseen piirtoikkunaan 
     a) nelikulmio, jonka vasen yläkulma on pisteessä \((160, 90)\) ja
        jonka leveys on 300 ja korkeus 500
     b) 
     

* Väri <<2>>
* Piirtoikkuna ja koordinaatisto <<3>>
* Vakio <<4>>
* Laskulauseke <<5>>
* Lauseke <<6>>
* Muuttuja <<7>>
* Ehdollinen suorittaminen <<8>>
* ~while~-silmukka <<9>>
* ~for~-silmukka <<10>>
* Pikseli <<11>>
  <<txt:pikseli>>
* Funktion määritteleminen <<12>>
* Animaatio <<13>>
* Aika <<14>>
* Hiiri <<15>>
* Satunnaisuus <<16>>
* Rekursio <<17>>
