#+INCLUDE: ohjelmointi-kappaleiden-yhteiset-asetukset.org

#+NAME: taulukko-ympyrat-annetut-x 
#+BEGIN_SRC org :exports none
20, 40, 90, 130, 170, 200, 300, 350, 470, 505, 550
#+END_SRC

* Taulukko
** Esimerkki
   Kirjoitetaan ohjelma, joka piirtää alla olevan kuvan. Kuvassa
   ympyröiden keskipisteitä ei ole arvottu satunnaisesti, vaan ne on
   annettu: call_taulukko-ympyrat-annetut-x().

   #+NAME: taulukko-ympyrat-annetuissa
   #+BEGIN_SRC processing :noweb yes
     size (600, 150);

     final int HALKAISIJA = 10;

     // määritellään taulukkovakio ja siinä olevat luvut
     final float[] XT = {<<taulukko-ympyrat-annetut-x>>};

     int i = 0; // taulukon indeksi, alkaa nollasta

     // taulukkoa käydään läpi niin kauan, kun indeksi on pienempi kuin
     // taulukon pituus
     while (i < XT.length)
     {
       ellipse (XT [i], height / 2.0, HALKAISIJA, HALKAISIJA);
       i++;
     }
   #+END_SRC

   Ympyröitä ei voi piirtää tavallisen ~while~-silmukan avulla, koska
   \(x\)-koordinaatit ovat epäsäännöllisissä kohdissa. Voisimme
   piirtää ympyrät kirjoittamalla yhden koodirivin kutakin ympyrää
   kohden, mutta se olisi kovin työlästä.

   Ongelma voidaan ratkaista helpoiten taulukon avulla.

** Taulukkovakio
   #+BEGIN_QUOTE
   /Taulukko/ on ohjelmoinnin tietorakenne, johon voidaan tallentaa
   järjestyksessä tietty määrä lukuja tai muita arvoja. Taulukossa
   oleviin lukuihin voidaan viitata niiden järjestysnumerolla, joka
   kirjoitetaan hakasulkujen ~[]~ sisään. Järjestysnumerot /alkavat
   nollasta/. Jos taulukon nimi on ~XT~, niin taulukon
   ensimmäinen luku on
   #+BEGIN_EXAMPLE
   XT [0]
   #+END_EXAMPLE
   Hakasuluissa olevaa kokonaislukua kutsutaan
   /indeksiksi/. Välilyönti taulukon nimen ja hakasulkujen välissä on
   valinnainen.

   Taulukon /pituus/ on siihen mahtuvien lukujen määrä. Jos taulukon
   nimi on ~XT~, niin taulukon pituus saadaan ohjelmassa
   lausekkeella 
   #+BEGIN_EXAMPLE
   XT.length
   #+END_EXAMPLE
   #+END_QUOTE
   
   Jos edellisessä esimerkissä olevat luvut
   call_taulukko-ympyrat-annetut-x() ovat taulukossa ~XT~, niin
   niihin voidaan viitata alla olevan kuvan mukaisesti. Taulukossa on
   11 lukua, jolloin indeksin suurin arvo on 10.
   #+NAME: taulukko-xkoordinaatit-taulukossa
   #+BEGIN_SRC asymptote :file taulukko-xkoordinaatit-taulukossa.svg :noweb yes
     size (8cm, 0);

     int[] coordinates = {<<taulukko-ympyrat-annetut-x>>};

     string tableSpecStr = "{r|";
     string headlineStr = "lauseke";
     string dataStr = "arvo";

     for (int i = 0; i < coordinates.length; ++i)
       {
         tableSpecStr += "c";
         headlineStr += "&" + "\texttt{XT} [" + (string) i + "]";
         dataStr += "&" + (string) (coordinates [i]);
       }
     tableSpecStr += "}";
     headlineStr += "\\";

     label ("\begin{tabular}" + tableSpecStr + headlineStr
            + "\hline " + dataStr + "\end{tabular}",
            (0, 0));
   #+END_SRC

   #+RESULTS: taulukko-xkoordinaatit-taulukossa
   [[file:taulukko-xkoordinaatit-taulukossa.svg]]

   #+BEGIN_QUOTE
   Jos taulukossa on $n$ lukua, niin taulukon indeksi on korkeintaan
   \((n - 1).\) Taulukon indeksin pienin arvo on aina 0.
   #+END_QUOTE

   Yllä oleva kuva on piirretty alla olevalla ohjelmalla. Ohjelmasta
   näkyy, miten taulukkovakio määritellään, ja miten taulukon luvut
   voidaan käydä läpi ~while~-silmukassa.

   #+BEGIN_SRC processing :noweb yes :exports code
   <<taulukko-ympyrat-annetuissa>>
   #+END_SRC
** Taulukkomuuttuja
   Taulukkomuuttujaa tarvitaan tyypillisesti silloin, kun muuttuvia
   tai satunnaisia lukujoukkoja käytetään ohjelmassa
   toistuvasti. Taulukkomuuttujan käyttö on hieman hankalampaa, koska
   taulukkomuuttujan määrittelyn lisäksi taulukolle täytyy erikseen
   varata tila.

   #+BEGIN_QUOTE
   Desimaalukuja sisältävä taulukkomuuttuja ~xt~ määritellään
   lausekkeella
   #+BEGIN_EXAMPLE
   float[] xt;
   #+END_EXAMPLE
   Taulukkoon varataan tilaa 20 luvulle lausekkeella
   #+BEGIN_EXAMPLE
   xt = new float [20];
   #+END_EXAMPLE
   Taulukkomuuttujan arvoa voidaan muuttaa sijoittamalla lukuja
   taulukkoon. Taulukon kolmanteen paikkaan (indeksi 2) sijoitetaan
   luku 75 lausekkeella
   #+BEGIN_EXAMPLE
   xt [2] = 75;
   #+END_EXAMPLE
   #+END_QUOTE

   [[file:taulukko-ympyrat-savy-sivu.org][Tällä sivulla]] olevassa animaatiossa arvotaan ensin ympyröiden
   keskipisteille satunnaiset \(x\)-koordinaatit. Sen jälkeen kaikki
   ympyrät piirretään kerran sekunnissa samalla satunnaisella
   värisävyllä. Koordinaatit kannattaa tallentaa taulukkoon, koska
   niitä tarvitaan toistuvasti piirtofunktiossa ~draw()~. Animaatio
   piirretään alla olevalla ohjelmakoodilla.

   #+BEGIN_SRC processing :exports code :noweb yes
   <<taulukko-ympyrat-savy>>
   #+END_SRC
** Esimerkki
   Yksittäinen piirtoikkunan piste kohdassa ~(x, y)~ voidaan piirtää
   funktiolla
   #+BEGIN_EXAMPLE
   void point (float x, float y)
   #+END_EXAMPLE
   Pisteen väri voidaan määrätä funktiolla ~stroke()~.
   
   [[file:taulukko-pisteet-sivu.org][Tällä sivulla]] oleva animaatio piirretään alla olevalla ohjelmakoodilla. 

   #+BEGIN_SRC processing :exports code :noweb yes
   <<taulukko-pisteet>>
   #+END_SRC


#+INCLUDE: taulukko-ympyrat-savy.org
#+INCLUDE: taulukko-pisteet.org

   
